from tkinter import*
from pytube import YouTube
from moviepy.editor import VideoFileClip
def get_movie ():
    name=name_info.get()
    url=url_info.get()
    yt=YouTube(url)
    print("We are downloading video...")
    video=yt.streams
    result=video.filter(progressive=False,subtype="mp4",res="360p")
    print("kfjfj",result[0])
    dest="adv-12/"
    fname=(name+".mp4")
    result[0].download(output_path=dest,filename=fname)
    print("Download finished...")
    movie_name.config(text=("影片名稱",yt.title))
    movie_time.config(text=("影片長度",yt.length,"秒"))
windows = Tk()
windows.title("My Gif")
url = Label(windows, text="請輸入下載網址", font=('Arial', 12))
url.grid(row=0, column=0)
url_info = Entry(windows)
url_info.grid(row=0, column=1)
name = Label(windows, text="請輸入影片名稱", font=('Arial', 12))
name.grid(row=1, column=0)
name_info = Entry(windows)
name_info.grid(row=1, column=1)
btn = Button(windows, text='Download', command=get_movie)
btn.grid(row=2, columnspan=2)
movie_name = Label(windows, text="")
movie_name.grid(row=3, column=0)
movie_time = Label(windows, text="")
movie_time.grid(row=4, column=0)
movie_res = Label(windows, text="")
movie_res.grid(row=5, column=0)
windows.geometry("300x150")
windows.mainloop()